name: Build GMSolutions Windows

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.24.5"
  RUST_VERSION: "1.75"

jobs:
  build:
    name: Build Windows EXE
    runs-on: windows-2022
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Build GMSolutions Client
        shell: pwsh
        run: |
          python3 build.py --flutter --hwcodec --portable
        env:
          RS_RENDEZVOUS_SERVER: ${{ secrets.RS_RENDEZVOUS_SERVER }}
          RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}

      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GMSolutions-Remote-Windows
          path: flutter/build/windows/x64/runner/Release/
